#!/bin/sh
#
# Simple Redis init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.

EXEC=/usr/local/bin/node
JSPATH=/home/kaija/source/heron/heron/heron.js

PIDFILE=/var/run/heron.pid

case "$1" in
    start)
            echo "Starting Heron server..."
            nohup $EXEC $JSPATH 1 > /dev/null 2>&1 &
            echo "$!" > $PIDFILE
        ;;
    stop)
            if [ ! -f $PIDFILE ]
            then
                echo "$PIDFILE does not exist, maybe process not running"
            else
                echo "Stopping Heron ..."
                PID=$(cat $PIDFILE)
                kill -9 $PID
                while [ -x /proc/$PIDFILE ]
                do
                    echo "Waiting Heron shutdown ..."
                    sleep 1
                done
                rm $PIDFILE
                echo "Heron Stopped"
            fi
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac
